### ISSUE TITLE
Too many values to unpack ERROR and question on historical data

### ISSUE THREAD

**Issue by troutct** [derek-adair/nflgame#138]
2 quick questions and looking for assistance/guidance on 1 error:

1) I've had nfldb for years and use it for fantasy football..I don't need LIVE scoring..just the game/status update after the weekly games are done. I've read that the NFL API has changed so no "live" scoring is possible anymore but historical data should work. I'm wondering..does "historical" mean only data from this point back (ie..no data for 2020 season will ever be available)..or does it mean we'll still be able to get data of future games but just not until the game is done being played ?

2) From running the NFLDB code I have data for 2020 week 1 in my game table but I'd like to have the full season schedule loaded to forecast stats, do strength of schedules, etc.  I've downloaded the NFLGAME code into an NFLGAME directory and tried running the update schedule but get the error below.  

Error:
c:\NFLGAME\scripts>c:\Python37\python nflgame-update-schedule
Traceback (most recent call last):
  File "nflgame-update-schedule", line 4, in <module>
    nflgame.update_sched.run()
  File "c:\Python37\lib\site-packages\nflgame\update_sched.py", line 192, in run
    sched, last = nflgame.sched._create_schedule(args.json_update_file)
ValueError: too many values to unpack (expected 2)

**Comment by james-childress** [comment]
+1 I'm getting this same error when I run `nflgame-update-schedule`

**Comment by RSABryan** [comment]
+1 yep, same error here, tia

**Comment by paulz1** [comment]
Do we have something on this? 
I have the same problem, the project is just unusable actually...
