### ISSUE TITLE
AttributeError: module 'nflgame.live' has no attribute '_cur_season_phase'

### ISSUE THREAD

**Issue by james-childress** [derek-adair/nflgame#140]
Hi,

I recently updated to python3 to begin using nflgame for the new season. I've tried following the initial set up directions running:
`python3 -m venv ~/python3`
`pip install nflgame-redux`
`nflgame-update-players`

When I run the last command, I get:
`Traceback (most recent call last):`
`  File "/Users/jachild/python3/bin/nflgame-update-players", line 4, in <module>`
`    nflgame.update_players.run()`
`  File "/Users/jachild/python3/lib/python3.6/site-packages/nflgame/update_players.py", line 360, in run`
`    phase = nflgame.live._cur_season_phase`
`AttributeError: module 'nflgame.live' has no attribute '_cur_season_phase'`

Is this a known issue? Should I be installing a different version?

Thanks

**Comment by RoboTums** [comment]
Hi,
I have the same issue-- I dug around in the site-packages/nflgame/update_players.py, and found that I could set the command
`nflgame-update-players --phase` to three options: POST, PRE, and REG. However, all three fail with the same error as OP. 

It seems that _cur_season_phase doesn't work when it's specified by the user.

**Comment by schoenbl** [comment]
I get the same issue. Has anyone found a solution?

**Comment by mickeelm** [comment]
See the other issues. The APIs are locked.

**Comment by schoenbl** [comment]
@mickeelm do you know of anywhere else that has access to current season play by play data?

**Comment by mickeelm** [comment]
Sorry I dont know, check the other threads/search around :)

**Comment by JimHewitt** [comment]
You can find a version of PBP data [here](https://github.com/guga31bb/nflfastR-raw/tree/master/raw).
