### ISSUE TITLE
The discord link is broken??

### ISSUE THREAD

**Issue by QuartzWarrior** [derek-adair/nflgame#144]
I need help but I can't join the discord... So here is my question:
My code:
```
import nflgame
def boi():
    game = nflgame.one(2011, 17, "NE", "BUF")
    print(game)
if __name__=='__main__':
    boi()
```
My result:

```
Traceback (most recent call last):
  File "/home/Quartz/Desktop/Python Random/Untitled-1.py", line 6, in <module>
    boi()
  File "/home/Quartz/Desktop/Python Random/Untitled-1.py", line 3, in boi
    game = nflgame.one(2011, 17, "NE", "BUF")
  File "/home/Quartz/.local/lib/python3.7/site-packages/nflgame/__init__.py", line 312, in one
    return nflgame.game.Game(**infos[0])
NameError: name 'nflgame' is not defined
```

**Comment by derek-adair** [comment]
Hey.  You need to make sure you have nflgame installed.  Pleas follow the numerous tutorials i've linked throughout.

I'll comb over things and fix the discord links but its pretty dead... maybe cuz the links broken? i dunno.  Good luck with your installation.
