### ISSUE TITLE
2016 Season Super Bowl listed as week 5, querying POST week 4 gives error

### ISSUE THREAD

**Issue by cruffenach** [derek-adair/nflgame#44]
This seemed wrong to me

```
>>> pp.pprint(nflgame.games(2016, kind="POST", week=4)[0].schedule)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cruffenach/Library/Python/2.7/lib/python/site-packages/nflgame/__init__.py", line 225, in games
    return list(games_gen(year, week, home, away, kind, started))
TypeError: 'NoneType' object is not iterable
>>> pp.pprint(nflgame.games(2016, kind="POST", week=5)[0].schedule)
{   u'away': u'NE',
    u'day': 5,
    u'eid': u'2017020500',
    u'gamekey': u'57167',
    u'home': u'ATL',
    u'meridiem': u'PM',
    u'month': 2,
    u'season_type': u'POST',
    u'time': u'6:30',
    u'wday': u'Sun',
    u'week': 5,
    u'year': 2016}
```

**Comment by ochawkeye** [comment]
we have no control over what week the NFL decides to assign the game to. in 2006 they called the Super Bowl week 5.

**Comment by cruffenach** [comment]
Huh, weird.

**Comment by ochawkeye** [comment]
I was a little quick to dismiss this one.  These are infrequent enough that we could probably catch them and either direct the user to query the correct week or just convert it for them.

An error isn't very useful.

**Comment by derek-adair** [comment]
What are other examples of them doing similar things?
