### ISSUE TITLE
nflgame-update-players wasn't working until I installed 2.0.1b2

### ISSUE THREAD

**Issue by geig3r** [derek-adair/nflgame#96]
Now it works but I'm getting too many redirects error from python.

`Loading games for REG 2019 week 10
Downloading team rosters...
14/33 complete. (42.42%)Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/nflgame-update-players", line 4, in <module>
    nflgame.update_players.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nflgame/update_players.py", line 400, in run
    for i, (team, soup) in enumerate(pool.imap(fetch, teams), 1):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 865, in next
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nflgame/update_players.py", line 399, in fetch
    return team, roster_soup(team)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nflgame/update_players.py", line 122, in roster_soup
    resp = requests.get(urls['roster'], params={'team':team})
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 165, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.`

**Comment by Coop197823** [comment]
please check out issue #90 as well as the latest pull request for the workaround.

**Comment by derek-adair** [comment]
JEEEEEEEEEEEEEEEZ what did I do last fall.  Not sure why 2.0.1b2 didn't get pushed to github.

**Comment by derek-adair** [comment]
This should be fixed in master.  Unsure if its in any pypi releases.

Closing b/c I clearly fixed this at some point? *shrug
