### ISSUE TITLE
Unable to get post game for 2018 and 2019 season

### ISSUE THREAD

**Issue by kalpitpant** [derek-adair/nflgame#97]
I am not able to get post games of 2018 and 2019 season using
nflgame.games(year=2018 , week= 1 , kind='POST' )

This same thing is working for season 2017. But not for season 2018 and 2019.

**Comment by derek-adair** [comment]
I'll take a look, thanks for the report.

**Comment by kalpitpant** [comment]
Hi Derek, 
Did you get a chance to look into this issue?

**Comment by Schweig** [comment]
I am also running into this issue

**Comment by kalpitpant** [comment]
Mine is working now. Actually you have to update your schedule.json as the matches are not there. So to make it work update your schedule.json.

**Comment by Schweig** [comment]
How do you update schedule.json is that thought the library or do I need to edit the file manually?

**Comment by ericspreher** [comment]
I just ran python.exe nflgame-update-schedule --year=2019 --phase=POST and it looks like it loaded week 1 and 2 of the schedule.json for me.

**Comment by midium** [comment]
To update it I've got to run `python update_sched.py --year=2019` command on library folder. Though at first it gaves me following error (I'm using python 3.8):

```
C:\Users\matteo.loro\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nflgame\sched.py:19: **SyntaxWarning: "is" with a literal. Did you mean "=="?
  if phase is 'POST':**
Traceback (most recent call last):
  File "update_sched.py", line 11, in <module>
    import nflgame
  File "C:\Users\matteo.loro\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nflgame\__init__.py", line 94, in <module>
    import nflgame.game  # noqa
  File "C:\Users\matteo.loro\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nflgame\game.py", line 15, in <module>
    import nflgame.sched
  File "C:\Users\matteo.loro\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nflgame\sched.py", line 99, in <module>
    games, last_updated = _create_schedule()
  File "C:\Users\matteo.loro\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nflgame\sched.py", line 82, in _create_schedule
    missing_weeks = check_missing_weeks(sched, year, phase)
  File "C:\Users\matteo.loro\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nflgame\sched.py", line 39, in check_missing_weeks
    missing_weeks.remove(stored_week)
ValueError: list.remove(x): x not in list
```

I've highlight the point that triggers me the fix. Inside sched.py file, at line 19 there is this:
`if phase is 'POST':`
I've got to change it to:
`if phase == 'POST':`
and now the update works. Not sure if this might could help someone
